- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "{{ db_endpoint }}"
    login_user: "{{ db_username }}"
    login_password: "{{ db_password }}"
    name: "{{ tooling_db_name }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "{{ db_endpoint }}" }
    - { regexp: '^admin', line: "{{ db_username }}" }
    - { regexp: '^tooling', line: "{{ tooling_db_name }}" }
    - { regexp: '^admin', line: "{{ db_password }}" }
