---
# defaults file for wordpress

# EFS File System ID
efs_id: "fs-09eda7e9d1234e139"

# EFS Access point for wordpress
tooling_fsap: "fsap-0082f3fc3211ce723"


# DB requirements
db_endpoint: "otl-identifier.cvo1k7yvqffy.us-east-1.rds.amazonaws.com"

db_username: "wale"

db_password: "devopspbl"

tooling_db_name: "toolingdb"